complexity:
  LongMethod:
    threshold: 60
  LargeClass:
    threshold: 600

style:
  MagicNumber:
    active: true
  WildcardImport:
    active: false

naming:
  FunctionNaming:
    active: true
    ignoreAnnotated:
      - Composable
